### PR TITLE
camera resource release fix

### PR DESCRIPTION
**Pull request by yousheakhan**
camera resource release issue fixed by stopping the mediastreamtracks on disabling the camera

### CODE REVIEW

**Review by zachdunn — CHANGES_REQUESTED** [review]
Thanks for the PR! Please use the existing 2 space tab convention so this diff isn't mostly formatting.

**Comment by yousheakhan** [comment]
using the 2 space tab convention, diff is now only the code changed

**Review by zachdunn — CHANGES_REQUESTED** [review]
Sorry I didn't catch this in the first review. You'll want to update the src files instead of the build https://github.com/onemightyroar/angular-camera/blob/develop/src/directives/angular-camera.coffee

**Comment by yousheakhan** [comment]
closing because the changes were in the build instead of the src file. Will generate a new pull request

**Pull request closed without merging**
